#
# New TLU Script Sept 6 2023 
# To be used with DUNE DAQ V4.4.3
#
# Updated by Shekhar Mishra for TLU Firmware version 7.3.0
# Based on based on comments received from Dennis Lindebaum and Stoyan Trilov
# June 21, 2024
#
# Modified by Shekhar Mishra to include DAPHNE-V3/V2 End Point Feb 6, 2024
#
# Sending Cosmic Trigger on Channel 5 (Limo 6) and Pulser on Channel 2
# Edited by Shekhar Mishra June 21, 2024
#
# Modified by Andrew Mogan to point to new DUNE DAQ area Nov. 2025

: "${LOG_PREFIX:=$(basename "${BASH_SOURCE[0]}")}"
source ../logging.sh

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    error "This script is intended to be executed directly, not sourced."
    return 1
fi

if [[ -z "$DBT_AREA_ROOT" ]]; then
    error "No DUNE DAQ environment setup."
    error "Navigate to the local DUNE DAQ build and run 'source env.sh'"
    exit 2
fi

dtsbutler io BOREAS_TLU_ICEBERG reset
sleep 2

dtsbutler mst BOREAS_TLU_ICEBERG synctime
sleep 2

dtsbutler mst BOREAS_TLU_ICEBERG faketrig-clear 0
sleep 2

dtsbutler mst BOREAS_TLU_ICEBERG faketrig-conf 0 2 2
sleep 2

# Signal 16777216 = 0x1000000 "= channel 25" (2**24)comes from the command decoder.
# The signal is generated by the command decode when the TLU issues timing commands. 
# It is looking for command 0x2, the rate of which is controlled if the final argument 
# of this line of the setup script:
# dtsbutler mst BOREAS_TLU_ICEBERG faketrig-conf 2 2 2
# So the final number 2 => 2 Hz
#
# The firmware update to V7.3.0 (June 15, 2024) allows the TLU to create HSI events from the timing system commands,
# The pulses now come from some specified timing commands, which is a separate block to the HSI.
# This is done by a "real" mechanism (i.e. externally to the HSI block).
# The command decoder which creates the events from the timing commands sends
# a "real" pulse to the HSI on a particular channel.

dtsbutler mst BOREAS_TLU_ICEBERG faketrig-conf 2 2 2 
sleep 2

# Received from Stoyan Trilov on June 3rd, 2024
# Received from Dennis Lindebaum on June 21, 2024
dtsbutler ept BOREAS_TLU_ICEBERG 0 enable -a 2 #enable the DTS endpoint inside the TLU
sleep 2

# The rising edge mask (i.e. -r 32) needs to include both channels. 
# In the DAQ configuration that "hsi_re_mask" is 16777248 = 16777216 + 32, 
# meaning the bitmask has both channels 6 and 25 active  (2**24) + (2**5)
# (equivalently, channels 5 and 24 if using 0 indexing).
dtsbutler hsi BOREAS_TLU_ICEBERG configure -r 16777248 -s 0 #enable capture for input 5 and 24 (counting from 0)
sleep 2
dtsbutler hsi BOREAS_TLU_ICEBERG start #start capture of signals
sleep 2
dtsbutler hsi BOREAS_TLU_ICEBERG readback #print contents of HSI buffer in firmware
sleep 2

# Setting for Puslser
dtsbutler mst BOREAS_TLU_ICEBERG align toggle-tx 2 --on
sleep 2
dtsbutler mst BOREAS_TLU_ICEBERG write-ept-reg 2 96 2 1
sleep 2
dtsbutler mst BOREAS_TLU_ICEBERG align toggle-tx 2 --off
sleep 2

# Align DAPHNE-V2 End point
dtsbutler mst BOREAS_TLU_ICEBERG align apply-delay 0x0020 0 0 --force
sleep 2

dtsbutler mst BOREAS_TLU_ICEBERG align toggle-tx 0x0020  --on > /dev/null
sleep 2
dtsbutler mst BOREAS_TLU_ICEBERG align toggle-tx 0x0020 --off > /dev/null
sleep 2

dtsbutler mst  BOREAS_TLU_ICEBERG align toggle-tx 0x0FFF
sleep 2

dtsbutler mst BOREAS_TLU_ICEBERG status
sleep 2
dtsbutler hsi BOREAS_TLU_ICEBERG readback
